name: Go package

on:
  workflow_call:
    inputs:
      service_path:
        required: true
        type: string
      service_name:
        required: true
        type: string
      go-version:
        required: false
        type: string
        default: '1.21'
      os:
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  build-and-test:
    name: Build, Lint & Test
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache-dependency-path: ${{ inputs.service_path }}/go.sum

      - name: Download dependencies
        working-directory: ${{ inputs.service_path }}
        run: go mod download

      - name: Run Tests
        working-directory: ${{ inputs.service_path }}
        run: go test -v ./...

  security-scan:
    name: Security Scan (SAST & SCA)
    needs: build-and-test
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run Govulncheck (SCA)
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          cd ${{ inputs.service_path }}
          govulncheck ./...

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ${{ inputs.service_path }}
          severity: 'CRITICAL'
          exit-code: '1'
          ignore-unfixed: true