name: Terraform Managment

on:
  workflow_dispatch:
    inputs:
      action:
        description: Acao do Terraform a ser executada
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION || 'us-east-1' }}
  BUCKET_STATE: ${{ secrets.TERRAFORM_STATE_BUCKET }}

jobs:
  setup:
    name: Verify Backend S3
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Mask sensitive strings in logs
        run: |
          echo "::add-mask::${{ secrets.AWS_SENSITIVE_IDENTITY }}"
      - run: |
          echo "Skipping explicit head-bucket check due to AWS Academy IAM restrictions. Terraform init will handle backend state interaction."

  base_infra:
    name: ECR and Serverless
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Mask sensitive strings in logs
        run: |
          echo "::add-mask::${{ secrets.AWS_SENSITIVE_IDENTITY }}"
      - run: |
          cat <<EOF > terraform/ecr/secrets.auto.tfvars
          ecr_repositories = ["auth-service", "flag-service", "targeting-service", "evaluation-service", "analytics-service"]
          EOF
          cd terraform/ecr
          terraform init -backend-config="bucket=$BUCKET_STATE" -backend-config="region=$AWS_REGION" -reconfigure
          terraform ${{ github.event.inputs.action }} -auto-approve
      - run: |
          cat <<EOF > terraform/serverless/secrets.auto.tfvars
          sqs_queue_name      = "togglemaster-evaluation-events"
          dynamodb_table_name = "ToggleMasterAnalytics"
          EOF
          cd terraform/serverless
          terraform init -backend-config="bucket=$BUCKET_STATE" -backend-config="region=$AWS_REGION" -reconfigure
          terraform ${{ github.event.inputs.action }} -auto-approve

  security_infra:
    name: Security (SSM Parameter Store)
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Mask sensitive strings in logs
        run: |
          echo "::add-mask::${{ secrets.AWS_SENSITIVE_IDENTITY }}"
      
      - name: Deploy SSM Parameters
        run: |
          cd terraform/security
          terraform init -backend-config="bucket=$BUCKET_STATE" -backend-config="region=$AWS_REGION" -reconfigure
          terraform ${{ github.event.inputs.action }} -auto-approve  

    data_infra:
    name: RDS and ElastiCache
    needs: [setup, security_infra]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Mask sensitive strings in logs
        run: |
          echo "::add-mask::${{ secrets.AWS_SENSITIVE_IDENTITY }}"
  
      
      - name: Deploy RDS
        run: |
          cd terraform/rds
          terraform init -backend-config="bucket=$BUCKET_STATE" -backend-config="region=$AWS_REGION" -reconfigure
          terraform ${{ github.event.inputs.action }} -auto-approve
      
      - name: Deploy ElastiCache
        run: |
          cd terraform/elasticache
          terraform init -backend-config="bucket=$BUCKET_STATE" -backend-config="region=$AWS_REGION" -reconfigure
          terraform ${{ github.event.inputs.action }} -auto-approve

  compute_infra:
    name: EKS Cluster
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      eks_sg_id: ${{ steps.export_sg.outputs.EKS_SG }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Mask sensitive strings in logs
        run: |
          echo "::add-mask::${{ secrets.AWS_SENSITIVE_IDENTITY }}"
      - run: |
          cd terraform/eks
          terraform init -backend-config="bucket=$BUCKET_STATE" -backend-config="region=$AWS_REGION" -reconfigure
          terraform ${{ github.event.inputs.action }} -auto-approve
      - id: export_sg
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          cd terraform/eks
          SG=$(terraform output -raw cluster_primary_security_group_id)
          echo "EKS_SG=$SG" >> $GITHUB_OUTPUT

  networking_infra:
    name: Networking Integrations
    needs: [data_infra, compute_infra]
    if: ${{ github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Mask sensitive strings in logs
        run: |
          echo "::add-mask::${{ secrets.AWS_SENSITIVE_IDENTITY }}"
      - env:
          EKS_SG: ${{ needs.compute_infra.outputs.eks_sg_id }}
        run: |
          cat <<EOF > terraform/networking/secrets.auto.tfvars
          eks_node_security_group = "$EKS_SG"
          rds_instances           = ["rds-postgres-auth", "rds-postgres-flag", "rds-postgres-targeting"]
          redis_cluster_id        = "togglemaster-redis"
          EOF
          cd terraform/networking
          terraform init -backend-config="bucket=$BUCKET_STATE" -backend-config="region=$AWS_REGION" -reconfigure
          terraform apply -auto-approve